version: '3'

services:
  klf-odoo15-db:
    image: postgres:14.0
    container_name: klf-odoo15-db
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo15@2021
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
#    networks:
#      - npm-network

  klf-odoo15:
    image: tvt253/odoo15:klf
    container_name: klf-odoo15
    user: root
    depends_on:
      - klf-odoo15-db
    ports:
      - "10013:8069"
#      - "20015:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=klf-odoo15-db
      - USER=odoo
      - PASSWORD=odoo15@2021
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      #- ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      - npm-network
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
#    ports:
#      - "10014:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: tvt253@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin@123
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
networks:
  npm-network:
    external: true

#volumes:
#  pgadmin-data:
