version: '3'

services:
  kly-odoo15-db:
    image: postgres:14
    container_name: klyfoods-odoo15-db
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo15@2021      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - npm-network

  kly-odoo15:
    image: odoo:15
    container_name: klyfoods-odoo15
    user: root
    depends_on:
      - kly-odoo15-db
    ports:
      - "10015:8069"
#      - "20015:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=kly-odoo15-db
      - USER=odoo
      - PASSWORD=odoo15@2021
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      - npm-network

networks:
  npm-network:
    external: true
